// This file was generated by ChatGPT parce que j'ai pas le temps ni les connaissances pour faire tout ça

/**
 * Hashes a string into a positive 32-bit integer using FNV-1a algorithm.
 * Produces very different outputs for similar strings.
 */
export function hashString(str: string): number {
  let hash = 2166136261;

  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }

  return Math.abs(hash);
}
